---
    - name: Install MySQL database
      apt:
        name: ['mysql-server', 'mysql-client']
        state: latest
      become: yes
      become_user: root

    - name: Start MySQL Service
      service:
        name: mysql
        state: started
        enabled: yes
      become: yes
      become_user: root

    - name: Create Application Database
      mysql_db: name={{ db_name }} state=present
      become: yes
      become_user: root

    - name: Create Database User
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_user_password }}"
        priv: '*.*:ALL'
        state: present
        host: '%'
      become: yes
      become_user: root

